# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U7eJ7CSuQJ_eP6ErF0ghWVXYwoR6jxjJ
"""

!pip install pycryptodome

!pip install crypto

from Crypto.Cipher import DES
from secrets import token_bytes

def get_key():
  key = token_bytes(8)
  print(f"key is{key} ")
  return key

def encrypt(mas, key):
  cipher = DES.new(key,DES.MODE_EAX)
  nonce = cipher.nonce
  cipher_text,tag = cipher.encrypt_and_digest(mas.encode('ascii'))
  return cipher_text,tag,nonce

mas = input("Enter your massage: ")
key = get_key()
ct,tg,nc = encrypt(mas, key)
print(f"Plain Text: {mas} \nCipher Text: {ct}")

def decrypt(ct,key,nonce,tag):
  cipher = DES.new(key,DES.MODE_EAX,nonce=nonce)
  plain_text = cipher.decrypt(ct)
  return plain_text

plain_text =decrypt(ct,key,nc,tg)
print("Main text is: ",plain_text)

